/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/er/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Label */
        post: operations["record_label_er_labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/er/queues/{queue}/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Task
         * @description The pair at ``position``, or the next unlabelled one (204 when the queue is done).
         */
        get: operations["task_er_queues__queue__task_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: database, blob store and LLM provider.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Process liveness only (used by the container healthcheck; touches no dependency).
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Listing */
        get: operations["get_listing_listings__platform___external_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calendar
         * @description The newest observation of each night in [start, end) — an observation, not a state.
         */
        get: operations["get_calendar_listings__platform___external_id__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claims
         * @description The listing's own claims, each beside its evidence; what has none yet says so.
         */
        get: operations["get_claims_listings__platform___external_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/geo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Geo
         * @description Distance to the coast and free-flow drive time, each a range over the blur circle.
         */
        get: operations["get_geo_listings__platform___external_id__geo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Offer
         * @description The listing's own all-in offer for this stay and group (never merged with others).
         */
        get: operations["get_offer_listings__platform___external_id__offer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/review-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Summary
         * @description Pros and cons that cite their reviews (one cached LLM call); null with too few reviews.
         */
        get: operations["get_review_summary_listings__platform___external_id__review_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reviews
         * @description The reviews the listing page showed (most recent stays first); names are not stored.
         */
        get: operations["get_reviews_listings__platform___external_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photo-labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Label */
        post: operations["post_label_photo_labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photo-labels/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_photo_labels_task_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenarios
         * @description The stay scenarios the catalog is captured for (config/scenarios.toml).
         */
        get: operations["get_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description A Persian query to ranked listings with reasons, and why the first one fits.
         */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalendarNightOut */
        CalendarNightOut: {
            /** Availability */
            availability: string;
            extra_guest_price: components["schemas"]["MoneyOut"] | null;
            /** Is Holiday */
            is_holiday: boolean | null;
            /** Min Nights */
            min_nights: number | null;
            /**
             * Night
             * Format: date
             */
            night: string;
            price: components["schemas"]["MoneyOut"] | null;
            provenance: components["schemas"]["ProvenanceOut"];
        };
        /** ClaimsOut */
        ClaimsOut: {
            /** Distances */
            distances: components["schemas"]["DistanceClaimOut"][];
            /** Features */
            features: components["schemas"]["FeatureClaimOut"][];
        };
        /** ContributionOut */
        ContributionOut: {
            /** Component */
            component: string;
            /** Normalized */
            normalized: number;
            /** Points */
            points: number;
            /** Weight */
            weight: number;
        };
        /** DatesOut */
        DatesOut: {
            /** Caveats */
            caveats: string[];
            /** Check In */
            check_in: string;
            /** Check Out */
            check_out: string;
            /** Flexible */
            flexible: boolean;
            /** Text */
            text: string;
        };
        /** DistanceClaimOut */
        DistanceClaimOut: {
            /** Evidence */
            evidence: string;
            evidence_provenance: components["schemas"]["ProvenanceOut"] | null;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Radius Assumed */
            radius_assumed: boolean;
            /** Target */
            target: string;
            /** Text */
            text: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "supported" | "consistent" | "not_confirmed" | "inconsistent" | "contradicted" | "shared" | "not_checked";
        };
        /** ExplanationOut */
        ExplanationOut: {
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /**
             * Source
             * @enum {string}
             */
            source: "llm" | "template";
            /** Text */
            text: string;
        };
        /** FeatureClaimOut */
        FeatureClaimOut: {
            /** Evidence */
            evidence: string;
            evidence_provenance: components["schemas"]["ProvenanceOut"] | null;
            /** Feature */
            feature: string;
            /**
             * Polarity
             * @enum {string}
             */
            polarity: "has" | "has_not";
            provenance: components["schemas"]["ProvenanceOut"];
            /** Span */
            span: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "supported" | "consistent" | "not_confirmed" | "inconsistent" | "contradicted" | "shared" | "not_checked";
        };
        /** GeoOut */
        GeoOut: {
            coast_m: components["schemas"]["GeoRangeOut"] | null;
            drive_s: components["schemas"]["GeoRangeOut"] | null;
            /** Origin */
            origin: string | null;
        };
        /**
         * GeoRangeOut
         * @description A measured quantity over the listing's blur circle (ADR-0013).
         */
        GeoRangeOut: {
            /** High */
            high: number;
            /** Low */
            low: number;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Radius Assumed */
            radius_assumed: boolean;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ProbeOut"];
            };
            /** Status */
            status: string;
            /** Summary */
            summary: string;
        };
        /** HostOut */
        HostOut: {
            /** Host */
            host: string;
            /** Median Interval S */
            median_interval_s: number | null;
            /** Min Interval S */
            min_interval_s: number | null;
            /** Platform */
            platform: string;
            /** Responses */
            responses: number;
        };
        /**
         * Label
         * @enum {string}
         */
        Label: "match" | "non_match" | "unsure";
        /** LabelIn */
        LabelIn: {
            label: components["schemas"]["Label"];
            /** Labeler */
            labeler: string;
            /** Pair */
            pair: string;
            /** Queue */
            queue: string;
            /** Seconds */
            seconds?: number | null;
        };
        /** LabelOut */
        LabelOut: {
            label: components["schemas"]["Label"];
            /** Labeled At */
            labeled_at: string;
            /** Pair */
            pair: string;
        };
        /** LabellingOut */
        LabellingOut: {
            /** Labelled */
            labelled: number;
            /** Queue */
            queue: string;
            /** Total */
            total: number;
        };
        /** ListingOut */
        ListingOut: {
            /** Area M2 */
            area_m2: number | null;
            /** Base Capacity */
            base_capacity: number | null;
            /** Bathrooms */
            bathrooms: number | null;
            /** Bedrooms */
            bedrooms: number | null;
            /** City */
            city: string | null;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Locality */
            locality: string | null;
            location: components["schemas"]["LocationOut"] | null;
            /** Max Capacity */
            max_capacity: number | null;
            /** Photos */
            photos: string[];
            /** Platform */
            platform: string;
            /** Platform Name */
            platform_name: string;
            /** Property Type */
            property_type: string | null;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Rating */
            rating: number | null;
            /** Rating Count */
            rating_count: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** LiveOut */
        LiveOut: {
            /** Status */
            status: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius M */
            radius_m: number | null;
        };
        /** MetricsOut */
        MetricsOut: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Hosts */
            hosts: components["schemas"]["HostOut"][];
            /** Labelling */
            labelling: components["schemas"]["LabellingOut"][];
            /** Llm Cap Usd */
            llm_cap_usd: number;
            /** Llm Spend */
            llm_spend: components["schemas"]["SpendOut"][];
            /** Llm Total Usd */
            llm_total_usd: number;
            /** Offers */
            offers: components["schemas"]["OffersOut"][];
            /** Platforms */
            platforms: components["schemas"]["PlatformOut"][];
        };
        /**
         * MoneyOut
         * @description Rial is exact; toman is for display. ``high`` null means "at least ``low``".
         */
        MoneyOut: {
            /** High Rial */
            high_rial: number | null;
            /** High Toman */
            high_toman: number | null;
            /** Low Rial */
            low_rial: number;
            /** Low Toman */
            low_toman: number;
        };
        /** NightOut */
        NightOut: {
            extra_guest_price: components["schemas"]["MoneyOut"];
            extra_guest_provenance: components["schemas"]["ProvenanceOut"];
            /** Extra Guests */
            extra_guests: number;
            /**
             * Night
             * Format: date
             */
            night: string;
            price: components["schemas"]["MoneyOut"];
            price_provenance: components["schemas"]["ProvenanceOut"];
        };
        /** OfferOut */
        OfferOut: {
            /** Age Hours */
            age_hours: number;
            /** Caveats */
            caveats: string[];
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /** Guests */
            guests: number;
            /** Kind */
            kind: ("exact" | "range" | "open") | null;
            /** Listing Id */
            listing_id: string;
            /** Nights */
            nights: components["schemas"]["NightOut"][];
            provenance: components["schemas"]["ProvenanceOut"];
            /** Stale */
            stale: boolean;
            /** Status */
            status: string;
            total: components["schemas"]["MoneyOut"] | null;
        };
        /** OffersOut */
        OffersOut: {
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Guests */
            guests: number;
            /** Listings */
            listings: number;
            /** Platform */
            platform: string;
            /** Scenario */
            scenario: string;
            /** Stale */
            stale: number;
        };
        /** PhotoLabelIn */
        PhotoLabelIn: {
            /**
             * Labeler
             * @default owner
             */
            labeler: string;
            /** Present */
            present: components["schemas"]["PhotoTag"][];
            /** Queue */
            queue: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * PhotoTag
         * @enum {string}
         */
        PhotoTag: "pool" | "jacuzzi" | "sea_view" | "forest" | "fireplace" | "barbecue";
        /** PhotoTaskOut */
        PhotoTaskOut: {
            /** Done */
            done: boolean;
            /** Labelled */
            labelled: number;
            /** Position */
            position: number;
            /** Present */
            present: components["schemas"]["PhotoTag"][];
            /** Queue */
            queue: string;
            /** Sha256 */
            sha256: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Total */
            total: number;
            /** Url */
            url: string;
        };
        /** PlatformOut */
        PlatformOut: {
            /** Coast Measured */
            coast_measured: number;
            /** Drive Routed */
            drive_routed: number;
            /** Listings */
            listings: number;
            /** Photo Coverage */
            photo_coverage: number;
            /** Photos Downloaded */
            photos_downloaded: number;
            /** Photos Selected */
            photos_selected: number;
            /** Photos Unfinished */
            photos_unfinished: number;
            /** Platform */
            platform: string;
            /** Sea Claim Listings */
            sea_claim_listings: number;
            /** Sea Contradicted High */
            sea_contradicted_high: number;
            /** Sea Contradicted Listings */
            sea_contradicted_listings: number;
            /** Sea Contradicted Low */
            sea_contradicted_low: number;
            /** Sea Measured Listings */
            sea_measured_listings: number;
            /** Sea Verdicts */
            sea_verdicts: {
                [key: string]: number;
            };
        };
        /** ProbeOut */
        ProbeOut: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /** Inputs */
            inputs: number;
            /**
             * Method
             * @enum {string}
             */
            method: "observed" | "derived" | "llm_extracted" | "human";
            /** Note */
            note?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Oldest Input At
             * Format: date-time
             */
            oldest_input_at: string;
            /** Snapshot Id */
            snapshot_id: string | null;
            source: components["schemas"]["SourceOut"] | null;
        };
        /** ResultOut */
        ResultOut: {
            /** Cautions */
            cautions: string[];
            /** Confirmed Features */
            confirmed_features: number;
            /** Contributions */
            contributions: components["schemas"]["ContributionOut"][];
            /** External Id */
            external_id: string;
            geo: components["schemas"]["GeoOut"] | null;
            /** Listing Id */
            listing_id: string;
            /** Photo */
            photo: string | null;
            /** Platform */
            platform: string;
            /** Platform Name */
            platform_name: string;
            /** Price Per Person Night Toman */
            price_per_person_night_toman: number | null;
            /** Score */
            score: number;
            /** Title */
            title: string;
            total: components["schemas"]["MoneyOut"] | null;
            total_provenance: components["schemas"]["ProvenanceOut"];
        };
        /** ReviewOut */
        ReviewOut: {
            /** Host Replied */
            host_replied: boolean;
            /** Id */
            id: string;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Rating */
            rating: number | null;
            /** Stayed On */
            stayed_on: string | null;
            /** Stayed Precision */
            stayed_precision: ("day" | "month") | null;
            /** Text */
            text: string | null;
        };
        /** ReviewSummaryOut */
        ReviewSummaryOut: {
            /** Cons */
            cons: components["schemas"]["SummaryPointOut"][];
            /** Pros */
            pros: components["schemas"]["SummaryPointOut"][];
            /** Reviews Given */
            reviews_given: number;
            /**
             * Source
             * @constant
             */
            source: "llm";
        };
        /** ScenarioOut */
        ScenarioOut: {
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /** Guests */
            guests: number[];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** SearchIn */
        SearchIn: {
            /** Drop */
            drop?: string[];
            /** Query */
            query: string;
        };
        /** SearchOut */
        SearchOut: {
            /** Budget Readings */
            budget_readings: {
                [key: string]: number;
            } | null;
            dates: components["schemas"]["DatesOut"] | null;
            /** Drive Coverage */
            drive_coverage: {
                [key: string]: number;
            };
            /** Excluded */
            excluded: {
                [key: string]: number;
            };
            explanation: components["schemas"]["ExplanationOut"] | null;
            /** Intent */
            intent: {
                [key: string]: unknown;
            };
            /** Missing */
            missing: string[];
            /** Places */
            places: string[];
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["ResultOut"][];
            /** Total Results */
            total_results: number;
            /** Unresolved Places */
            unresolved_places: string[];
        };
        /** SegmentOut */
        SegmentOut: {
            provenance: components["schemas"]["ProvenanceOut"] | null;
            /** Slot */
            slot: string | null;
            /** Text */
            text: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Platform */
            platform: string;
            /** Url */
            url: string;
        };
        /** SpendOut */
        SpendOut: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Failed */
            failed: number;
            /** Model */
            model: string;
            /** Task */
            task: string;
        };
        /** SummaryPointOut */
        SummaryPointOut: {
            /** Review Ids */
            review_ids: string[];
            /** Single Opinion */
            single_opinion: boolean;
            /** Text */
            text: string;
        };
        /** TagOut */
        TagOut: {
            code: components["schemas"]["PhotoTag"];
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    record_label_er_labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_er_queues__queue__task_get: {
        parameters: {
            query?: {
                labeler?: string;
                position?: number | null;
            };
            header?: never;
            path: {
                queue: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    get_listing_listings__platform___external_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_listings__platform___external_id__calendar_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarNightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claims_listings__platform___external_id__claims_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geo_listings__platform___external_id__geo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_offer_listings__platform___external_id__offer_get: {
        parameters: {
            query: {
                check_in: string;
                check_out: string;
                guests: number;
            };
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_summary_listings__platform___external_id__review_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummaryOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviews_listings__platform___external_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
        };
    };
    post_label_photo_labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoLabelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_photo_labels_task_get: {
        parameters: {
            query?: {
                queue?: string;
                labeler?: string;
                position?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoTaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
