/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/er/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Label */
        post: operations["record_label_er_labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/er/queues/{queue}/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Task
         * @description The pair at ``position``, or the next unlabelled one (204 when the queue is done).
         */
        get: operations["task_er_queues__queue__task_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: database, blob store and LLM provider.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Process liveness only (used by the container healthcheck; touches no dependency).
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Listing */
        get: operations["get_listing_listings__platform___external_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calendar
         * @description The newest observation of each night in [start, end) — an observation, not a state.
         */
        get: operations["get_calendar_listings__platform___external_id__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Offer
         * @description The listing's own all-in offer for this stay and group (never merged with others).
         */
        get: operations["get_offer_listings__platform___external_id__offer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{platform}/{external_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reviews
         * @description The reviews the listing page showed (most recent stays first); names are not stored.
         */
        get: operations["get_reviews_listings__platform___external_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenarios
         * @description The stay scenarios the catalog is captured for (config/scenarios.toml).
         */
        get: operations["get_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalendarNightOut */
        CalendarNightOut: {
            /** Availability */
            availability: string;
            extra_guest_price: components["schemas"]["MoneyOut"] | null;
            /** Is Holiday */
            is_holiday: boolean | null;
            /** Min Nights */
            min_nights: number | null;
            /**
             * Night
             * Format: date
             */
            night: string;
            price: components["schemas"]["MoneyOut"] | null;
            provenance: components["schemas"]["ProvenanceOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ProbeOut"];
            };
            /** Status */
            status: string;
            /** Summary */
            summary: string;
        };
        /**
         * Label
         * @enum {string}
         */
        Label: "match" | "non_match" | "unsure";
        /** LabelIn */
        LabelIn: {
            label: components["schemas"]["Label"];
            /** Labeler */
            labeler: string;
            /** Pair */
            pair: string;
            /** Queue */
            queue: string;
            /** Seconds */
            seconds?: number | null;
        };
        /** LabelOut */
        LabelOut: {
            label: components["schemas"]["Label"];
            /** Labeled At */
            labeled_at: string;
            /** Pair */
            pair: string;
        };
        /** ListingOut */
        ListingOut: {
            /** Area M2 */
            area_m2: number | null;
            /** Base Capacity */
            base_capacity: number | null;
            /** Bathrooms */
            bathrooms: number | null;
            /** Bedrooms */
            bedrooms: number | null;
            /** City */
            city: string | null;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Locality */
            locality: string | null;
            location: components["schemas"]["LocationOut"] | null;
            /** Max Capacity */
            max_capacity: number | null;
            /** Photos */
            photos: string[];
            /** Platform */
            platform: string;
            /** Platform Name */
            platform_name: string;
            /** Property Type */
            property_type: string | null;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Rating */
            rating: number | null;
            /** Rating Count */
            rating_count: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** LiveOut */
        LiveOut: {
            /** Status */
            status: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius M */
            radius_m: number | null;
        };
        /**
         * MoneyOut
         * @description Rial is exact; toman is for display. ``high`` null means "at least ``low``".
         */
        MoneyOut: {
            /** High Rial */
            high_rial: number | null;
            /** High Toman */
            high_toman: number | null;
            /** Low Rial */
            low_rial: number;
            /** Low Toman */
            low_toman: number;
        };
        /** NightOut */
        NightOut: {
            extra_guest_price: components["schemas"]["MoneyOut"];
            extra_guest_provenance: components["schemas"]["ProvenanceOut"];
            /** Extra Guests */
            extra_guests: number;
            /**
             * Night
             * Format: date
             */
            night: string;
            price: components["schemas"]["MoneyOut"];
            price_provenance: components["schemas"]["ProvenanceOut"];
        };
        /** OfferOut */
        OfferOut: {
            /** Age Hours */
            age_hours: number;
            /** Caveats */
            caveats: string[];
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /** Guests */
            guests: number;
            /** Kind */
            kind: ("exact" | "range" | "open") | null;
            /** Listing Id */
            listing_id: string;
            /** Nights */
            nights: components["schemas"]["NightOut"][];
            provenance: components["schemas"]["ProvenanceOut"];
            /** Stale */
            stale: boolean;
            /** Status */
            status: string;
            total: components["schemas"]["MoneyOut"] | null;
        };
        /** ProbeOut */
        ProbeOut: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
        };
        /** ProvenanceOut */
        ProvenanceOut: {
            /** Inputs */
            inputs: number;
            /**
             * Method
             * @enum {string}
             */
            method: "observed" | "derived" | "llm_extracted" | "human";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Oldest Input At
             * Format: date-time
             */
            oldest_input_at: string;
            /** Snapshot Id */
            snapshot_id: string | null;
            source: components["schemas"]["SourceOut"] | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Host Replied */
            host_replied: boolean;
            /** Id */
            id: string;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Rating */
            rating: number | null;
            /** Stayed On */
            stayed_on: string | null;
            /** Stayed Precision */
            stayed_precision: ("day" | "month") | null;
            /** Text */
            text: string | null;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /**
             * Check In
             * Format: date
             */
            check_in: string;
            /**
             * Check Out
             * Format: date
             */
            check_out: string;
            /** Guests */
            guests: number[];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Platform */
            platform: string;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    record_label_er_labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_er_queues__queue__task_get: {
        parameters: {
            query?: {
                labeler?: string;
                position?: number | null;
            };
            header?: never;
            path: {
                queue: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveOut"];
                };
            };
        };
    };
    get_listing_listings__platform___external_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_listings__platform___external_id__calendar_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarNightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_offer_listings__platform___external_id__offer_get: {
        parameters: {
            query: {
                check_in: string;
                check_out: string;
                guests: number;
            };
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviews_listings__platform___external_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
}
